In [1]:
!pip install dateparser

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 2.7 MB/s eta 0:00:00


In [3]:
import spacy
import dateparser

In [4]:
!python -m spacy download ru_core_news_md


2023-12-21 18:16:37.322011: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-21 18:16:37.322076: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-21 18:16:37.323840: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-21 18:16:38.574398: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 MB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 57.7 MB/s eta 0:00:00
✔

In [6]:
def extract_named_entities_spacy_russian_bioes(text):
    nlp = spacy.load("ru_core_news_md")
    doc = nlp(text)

    named_entities = [(ent.text, ent.start_char, ent.end_char, ent.label_) for ent in doc.ents]

    for sent in doc.sents:
        for i, token in enumerate(sent):
            if token.text.lower() == 'год' and i > 0 and sent[i - 1].is_digit and i < len(sent) - 1 and not sent[i + 1].is_alpha:
                continue
            if dateparser.parse(token.text, languages=['ru']):
                start, end = token.idx, token.idx + len(token)
                named_entities.append((token.text, start, end, "DATE"))

    return named_entities

def map_to_russian_labels(entity_type):
    label_mapping = {
        "PER": "Человек",
        "LOC": "Локация",
        "ORG": "Организация",
        "DATE": "Дата",
    }
    return label_mapping.get(entity_type, entity_type)

def print_entities(entities):
    for entity, start, end, entity_type in entities:
        russian_label = map_to_russian_labels(entity_type)
        print(f"{entity}: {russian_label} ({start}-{end})")

if __name__ == "__main__":
    input_text = input()
    entities = extract_named_entities_spacy_russian_bioes(input_text)
    print_entities(entities)

Стерлитамак — город в России, второй (после Уфы) по численности населения город в Башкирии, административный центр Стерлитамакского района, в состав которого не входит. Город республиканского значения, образует муниципальное образование Городской округ город Стерлитамак как единственный населённый пункт в его составе. Крупный центр химической промышленности и машиностроения, один из центров Стерлитамакской агломерации. Основан в 1735 году как почтовая станция Ашкадарский Ям, статус города присвоен в 1781 году. В прошлом уездный город Уфимской области Уфимского наместничества (1781/82–1796)год; Оренбургской губернии (1796–1865)год, Уфимской губернии (1865–1920)год, столица Автономной Советской Башкирской Республики (1919—1922)год, а также административный центр Стерлитамакского кантона (1920—1930)год и Стерлитамакской области БАССР (1952—1953)год
России: Локация (22-28)
Уфы: Локация (44-47)
Башкирии: Локация (82-90)
Стерлитамакского района: Локация (115-138)
Городской округ: Локация (23

Стерлитамак — город в России, второй (после Уфы) по численности населения город в Башкирии, административный центр Стерлитамакского района, в состав которого не входит. Город республиканского значения, образует муниципальное образование Городской округ город Стерлитамак как единственный населённый пункт в его составе. Крупный центр химической промышленности и машиностроения, один из центров Стерлитамакской агломерации. Основан в 1735 году как почтовая станция Ашкадарский Ям, статус города присвоен в 1781 году. В прошлом уездный город Уфимской области Уфимского наместничества (1781/82–1796)год; Оренбургской губернии (1796–1865)год, Уфимской губернии (1865–1920)год, столица Автономной Советской Башкирской Республики (1919—1922)год, а также административный центр Стерлитамакского кантона (1920—1930)год и Стерлитамакской области БАССР (1952—1953)год